apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openvscodeserver-helmchart.fullname" . }}
  labels:
    {{- include "openvscodeserver-helmchart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openvscodeserver-helmchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openvscodeserver-helmchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openvscodeserver-helmchart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --connectionToken {{ .Values.accessToken }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /?tkn={{ .Values.accessToken }}
              port: http
          readinessProbe:
            httpGet:
              path: /?tkn={{ .Values.accessToken }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistentVolumes.enabled }}
          {{- range .Values.deployment.volumeMounts }}
          volumeMounts:
          - mountPath: {{ .mountPath }}
            name: {{ .name }}
          {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistentVolumes.enabled }}
      volumes:
      {{- range .Values.persistentVolumes.volumes }}
      - name: {{ .metadata.name }}
        persistentVolumeClaim:
          claimName: {{ .metadata.name }}
      {{- end }}
      {{- end }}
